USE `green-cart`;

insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (1, 'amcanellye0@gmail.com', 'Ashe', 'McAnellye', 'Credit Card', 5, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (2, 'nchark1@canalblog.com', 'Nanine', 'Chark', 'Debit Card', 4, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (3, 'ecoultas2@mozilla.org', 'Ediva', 'Coultas', 'Credit Card', 4, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (4, 'cchiene3@cyberchimps.com', 'Chauncey', 'Chiene', 'Credit Card', 7, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (5, 'egravey4@engadget.com', 'Eldridge', 'Gravey', 'Debit Card', 6, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (6, 'tstorr5@cafepress.com', 'Terza', 'Storr', 'Debit Card', 5, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (7, 'cburn6@domainmarket.com', 'Candy', 'Burn', 'EBT', 4, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (8, 'ocroisier7@howstuffworks.com', 'Odie', 'Croisier', 'Debit Card', 3, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (9, 'nflay8@squidoo.com', 'Noam', 'Flay', 'EBT', 3, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (10, 'mbrimham9@deliciousdays.com', 'Morie', 'Brimham', 'EBT', 5, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (11, 'igaffneya@springer.com', 'Illa', 'Gaffney', 'EBT', 5, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (12, 'ttreverb@nhs.uk', 'Tony', 'Trever', 'Credit Card', 4, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (13, 'rwardlawc@microsoft.com', 'Rennie', 'Wardlaw', 'EBT', 6, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (14, 'hhempshalld@paypal.com', 'Hilliard', 'Hempshall', 'EBT', 1, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (15, 'amaidese@wikipedia.org', 'Aharon', 'Maides', 'Debit Card', 5, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (16, 'aorrellf@so-net.ne.jp', 'Arlie', 'Orrell', 'Credit Card', 3, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (17, 'jbillamg@slashdot.org', 'Jud', 'Billam', 'Debit Card', 5, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (18, 'mtaylersonh@msu.edu', 'Madelyn', 'Taylerson', 'Debit Card', 6, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (19, 'bcollardi@csmonitor.com', 'Blanch', 'Collard', 'Credit Card', 7, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (20, 'anessj@newyorker.com', 'Antoinette', 'Ness', 'Credit Card', 4, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (21, 'phaseldinek@people.com.cn', 'Pietrek', 'Haseldine', 'EBT', 4, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (22, 'ringlishl@engadget.com', 'Rooney', 'Inglish', 'Debit Card', 3, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (23, 'tmccaguem@answers.com', 'Tabbatha', 'McCague', 'Credit Card', 6, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (24, 'diannellon@opera.com', 'Dave', 'Iannello', 'Credit Card', 1, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (25, 'tgorvino@loc.gov', 'Tallie', 'Gorvin', 'Credit Card', 6, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (26, 'ochanningp@technorati.com', 'Odelinda', 'Channing', 'EBT', 3, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (27, 'egarrisonq@prlog.org', 'Erv', 'Garrison', 'Debit Card', 7, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (28, 'sbagwellr@hp.com', 'Shelley', 'Bagwell', 'Debit Card', 1, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (29, 'vcorstorphines@example.com', 'Viviana', 'Corstorphine', 'EBT', 5, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (30, 'jbrindlet@123-reg.co.uk', 'Jonis', 'Brindle', 'Debit Card', 6, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (31, 'cscrubyu@4shared.com', 'Calvin', 'Scruby', 'Debit Card', 4, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (32, 'cspitellv@youtu.be', 'Christean', 'Spitell', 'Credit Card', 5, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (33, 'hwarstallw@delicious.com', 'Harland', 'Warstall', 'EBT', 3, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (34, 'pisittx@hud.gov', 'Parry', 'Isitt', 'Debit Card', 7, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (35, 'cruseliny@prlog.org', 'Constancy', 'Ruselin', 'Debit Card', 5, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (36, 'gsarfatz@wunderground.com', 'Guinna', 'Sarfat', 'EBT', 1, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (37, 'msenten10@cafepress.com', 'Maud', 'Senten', 'Debit Card', 6, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (38, 'bgruszczak11@loc.gov', 'Berenice', 'Gruszczak', 'Credit Card', 2, true);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (39, 'mdykes12@e-recht24.de', 'Minnaminnie', 'Dykes', 'EBT', 1, false);
insert into User (UserId, Email, FirstName, LastName, PaymentMethod, FamilySize, Notifications) values (40, 'notto13@phoca.cz', 'Nicol', 'Otto', 'Debit Card', 2, false);
