use `green-cart`;

insert into Employee (EmpId, Name, Email, Position) values (1, 'Jenelle Wilderspoon', 'jwilderspoon0@fda.gov', 'UX Designer');
insert into Employee (EmpId, Name, Email, Position) values (2, 'Jewelle Portal', 'jportal1@goodreads.com', 'Customer Support');
insert into Employee (EmpId, Name, Email, Position) values (3, 'Ilise Mair', 'imair2@seesaa.net', 'UX Designer');
insert into Employee (EmpId, Name, Email, Position) values (4, 'Meade Mitchard', 'mmitchard3@theguardian.com', 'UX Designer');
insert into Employee (EmpId, Name, Email, Position) values (5, 'Karoly Gullen', 'kgullen4@cdc.gov', 'Marketing Specialist');
insert into Employee (EmpId, Name, Email, Position) values (6, 'Lyle Daulby', 'ldaulby5@seattletimes.com', 'UX Designer');
insert into Employee (EmpId, Name, Email, Position) values (7, 'Dari Tribbeck', 'dtribbeck6@cafepress.com', 'Operations Manager');
insert into Employee (EmpId, Name, Email, Position) values (8, 'Terrijo Hegge', 'thegge7@hc360.com', 'Food Safety Officer');
insert into Employee (EmpId, Name, Email, Position) values (9, 'Gibby Bartoleyn', 'gbartoleyn8@discovery.com', 'Food Safety Officer');
insert into Employee (EmpId, Name, Email, Position) values (10, 'Barton Mundee', 'bmundee9@themeforest.net', 'Software Engineer');
insert into Employee (EmpId, Name, Email, Position) values (11, 'Cary McNeilley', 'cmcneilleya@va.gov', 'UX Designer');
insert into Employee (EmpId, Name, Email, Position) values (12, 'Bernardo Egiloff', 'begiloffb@ftc.gov', 'Food Safety Officer');
insert into Employee (EmpId, Name, Email, Position) values (13, 'Ev Cramer', 'ecramerc@guardian.co.uk', 'Product Manager');
insert into Employee (EmpId, Name, Email, Position) values (14, 'Michell Sommerly', 'msommerlyd@ucoz.com', 'Inventory Manager');
insert into Employee (EmpId, Name, Email, Position) values (15, 'Arlana Simonnot', 'asimonnote@who.int', 'Customer Support');
insert into Employee (EmpId, Name, Email, Position) values (16, 'Thelma Alldre', 'talldref@zimbio.com', 'Data Analyst');
insert into Employee (EmpId, Name, Email, Position) values (17, 'Octavius Jubert', 'ojubertg@facebook.com', 'Software Engineer');
insert into Employee (EmpId, Name, Email, Position) values (18, 'Rochester Sarfass', 'rsarfassh@google.ca', 'Product Manager');
insert into Employee (EmpId, Name, Email, Position) values (19, 'Lamont Sampey', 'lsampeyi@bravesites.com', 'Marketing Specialist');
insert into Employee (EmpId, Name, Email, Position) values (20, 'Minette MacConnal', 'mmacconnalj@springer.com', 'Food Safety Officer');
insert into Employee (EmpId, Name, Email, Position) values (21, 'Michel Jonk', 'mjonkk@cargocollective.com', 'Inventory Manager');
insert into Employee (EmpId, Name, Email, Position) values (22, 'Ulick Baudic', 'ubaudicl@vinaora.com', 'UX Designer');
insert into Employee (EmpId, Name, Email, Position) values (23, 'Leonora Arrow', 'larrowm@hostgator.com', 'Customer Support');
insert into Employee (EmpId, Name, Email, Position) values (24, 'Rooney Peebles', 'rpeeblesn@wix.com', 'Customer Support');
insert into Employee (EmpId, Name, Email, Position) values (25, 'Selina Routledge', 'sroutledgeo@cafepress.com', 'Customer Support');
insert into Employee (EmpId, Name, Email, Position) values (26, 'Ester Ianetti', 'eianettip@e-recht24.de', 'Product Manager');
insert into Employee (EmpId, Name, Email, Position) values (27, 'Inglebert Whitelock', 'iwhitelockq@merriam-webster.com', 'Software Engineer');
insert into Employee (EmpId, Name, Email, Position) values (28, 'Ameline Salamon', 'asalamonr@icq.com', 'Data Analyst');
insert into Employee (EmpId, Name, Email, Position) values (29, 'Kassey MacAughtrie', 'kmacaughtries@sakura.ne.jp', 'Marketing Specialist');
insert into Employee (EmpId, Name, Email, Position) values (30, 'Mitchel Sibthorp', 'msibthorpt@fema.gov', 'Marketing Specialist');
