use `green-cart`;

insert into 03_Employee (EmpId, Name, Email, Position) values (1, 'Cash Guillain', 'cguillain0@unc.edu', 'Marketing Specialist');
insert into 03_Employee (EmpId, Name, Email, Position) values (2, 'Juana Osment', 'josment1@sun.com', 'Food Safety Officer');
insert into 03_Employee (EmpId, Name, Email, Position) values (3, 'Roda Chicco', 'rchicco2@etsy.com', 'Food Safety Officer');
insert into 03_Employee (EmpId, Name, Email, Position) values (4, 'Violetta Denton', 'vdenton3@bloglines.com', 'Customer Support');
insert into 03_Employee (EmpId, Name, Email, Position) values (5, 'Melany McCaw', 'mmccaw4@oakley.com', 'Product Manager');
insert into 03_Employee (EmpId, Name, Email, Position) values (6, 'Charley Heales', 'cheales5@networksolutions.com', 'Software Engineer');
insert into 03_Employee (EmpId, Name, Email, Position) values (7, 'Wylma De Andisie', 'wde6@technorati.com', 'Customer Support');
insert into 03_Employee (EmpId, Name, Email, Position) values (8, 'Gerald Duncklee', 'gduncklee7@webnode.com', 'UX Designer');
insert into 03_Employee (EmpId, Name, Email, Position) values (9, 'Vida Testo', 'vtesto8@nbcnews.com', 'Food Safety Officer');
insert into 03_Employee (EmpId, Name, Email, Position) values (10, 'Rice Chellam', 'rchellam9@tiny.cc', 'Food Safety Officer');
insert into 03_Employee (EmpId, Name, Email, Position) values (11, 'Derby Adcocks', 'dadcocksa@archive.org', 'Data Analyst');
insert into 03_Employee (EmpId, Name, Email, Position) values (12, 'Leola Bottlestone', 'lbottlestoneb@elpais.com', 'Software Engineer');
insert into 03_Employee (EmpId, Name, Email, Position) values (13, 'Blondell O''Leary', 'bolearyc@disqus.com', 'Food Safety Officer');
insert into 03_Employee (EmpId, Name, Email, Position) values (14, 'Lula Veel', 'lveeld@addthis.com', 'Customer Support');
insert into 03_Employee (EmpId, Name, Email, Position) values (15, 'Ashien Ilyinski', 'ailyinskie@abc.net.au', 'Operations Manager');
insert into 03_Employee (EmpId, Name, Email, Position) values (16, 'Brandie Laurisch', 'blaurischf@auda.org.au', 'Data Analyst');
insert into 03_Employee (EmpId, Name, Email, Position) values (17, 'Giovanna Deplacido', 'gdeplacidog@devhub.com', 'Data Analyst');
insert into 03_Employee (EmpId, Name, Email, Position) values (18, 'Rodd Stinchcombe', 'rstinchcombeh@amazon.co.uk', 'UX Designer');
insert into 03_Employee (EmpId, Name, Email, Position) values (19, 'Jena Caesman', 'jcaesmani@t-online.de', 'Food Safety Officer');
insert into 03_Employee (EmpId, Name, Email, Position) values (20, 'Sutton Fairleigh', 'sfairleighj@comcast.net', 'Data Analyst');
insert into 03_Employee (EmpId, Name, Email, Position) values (21, 'Sunny Borthwick', 'sborthwickk@google.ca', 'Software Engineer');
insert into 03_Employee (EmpId, Name, Email, Position) values (22, 'Kingsley Key', 'kkeyl@alibaba.com', 'Inventory Manager');
insert into 03_Employee (EmpId, Name, Email, Position) values (23, 'Gwen Chidwick', 'gchidwickm@hao123.com', 'Inventory Manager');
insert into 03_Employee (EmpId, Name, Email, Position) values (24, 'Daune Broader', 'dbroadern@narod.ru', 'Marketing Specialist');
insert into 03_Employee (EmpId, Name, Email, Position) values (25, 'Constantine Shawdforth', 'cshawdfortho@simplemachines.org', 'Inventory Manager');
insert into 03_Employee (EmpId, Name, Email, Position) values (26, 'Stuart Stoggell', 'sstoggellp@senate.gov', 'Software Engineer');
insert into 03_Employee (EmpId, Name, Email, Position) values (27, 'Elana Knell', 'eknellq@istockphoto.com', 'Operations Manager');
insert into 03_Employee (EmpId, Name, Email, Position) values (28, 'Parsifal Wortman', 'pwortmanr@behance.net', 'Software Engineer');
insert into 03_Employee (EmpId, Name, Email, Position) values (29, 'Liva Harvie', 'lharvies@opera.com', 'Customer Support');
insert into 03_Employee (EmpId, Name, Email, Position) values (30, 'Orville Covey', 'ocoveyt@mediafire.com', 'UX Designer');
