use `green-cart`;

insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (1, 3, 'Ground Beef', 4, 'Meat', 73, 81);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (2, 5, 'Ice Cream', 17, 'Frozen', 41, 42);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (3, 1, 'Whole Milk', 16, 'Dairy', 35, 30);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (4, 5, 'Frozen Pizza', 14, 'Frozen', 5, 57);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (5, 8, 'Brown Rice', 18, 'Grain', 31, 19);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (6, 6, 'Sparkling Water', 15, 'Beverages', 6, 63);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (7, 7, 'Ketchup', 7, 'Condiments', 98, 71);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (8, 2, 'Apples', 18, 'Produce', 3, 69);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (9, 7, 'Mustard', 20, 'Condiments', 42, 13);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (10, 7, 'Soy Sauce', 1, 'Condiments', 68, 64);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (11, 7, 'Hot Sauce', 9, 'Condiments', 27, 34);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (12, 8, 'Pasta', 14, 'Grains', 58, 82);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (13, 1, 'Cheddar Cheese', 13, 'Dairy', 93, 75);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (14, 2, 'Lettuce', 17, 'Produce', 90, 10);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (15, 5, 'Frozen Chicken Tenders', 10, 'Frozen', 92, 40);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (16, 2, 'Tomatoes', 12, 'Produce', 23, 2);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (17, 7, 'Mayo', 19, 'Condiments', 67, 22);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (18, 4, 'Salmon', 2, 'Seafood', 75, 59);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (19, 3, 'Bacon', 14, 'Meat', 31, 69);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (20, 5, 'Frozen Waffles', 5, 'Frozen', 33, 50);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (21, 8, 'White Rice', 18, 'Grains', 2, 89);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (22, 6, 'Green Tea', 14, 'Beverages', 69, 83);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (23, 1, 'Greek Yogurt', 9, 'Dairy', 95, 52);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (24, 1, 'Sour Cream', 16, 'Dairy', 57, 4);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (25, 6, 'Orange Juice', 12, 'Beverages', 68, 12);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (26, 7, 'Olive Oil', 3, 'Condiments', 100, 2);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (27, 2, 'Spinach', 20, 'Produce', 27, 76);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (28, 3, 'Chicken Breast', 11, 'Meat', 21, 27);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (29, 6, 'Coffee', 7, 'Beverages', 98, 76);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (30, 8, 'Bread', 11, 'Grains', 48, 17);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (31, 8, 'Quinoa', 3, 'Grains', 73, 74);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (32, 6, 'Lemonade', 5, 'Beverages', 23, 87);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (33, 7, 'Ranch', 11, 'Condiments', 94, 23);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (34, 5, 'Frozen Breakfast Burritos', 20, 'Frozen', 52, 23);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (35, 8, 'English Muffin', 4, 'Grains', 65, 85);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (36, 6, 'Coconut Water', 15, 'Beverages', 98, 9);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (37, 7, 'Bbq Sauce', 15, 'Condiments', 94, 49);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (38, 6, 'Arizona Iced Tea', 14, 'Beverages', 92, 17);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (39, 3, 'Pork Chops', 3, 'Meat', 63, 98);
insert into FoodGlobal (FoodId, CategoryId, Name, UnitPrice, Category, DefaultSealedShelfLife , DefaultOpenShelfLife ) values (40, 1, 'Butter', 4, 'Dairy', 63, 9);