use `green-cart`;

insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (1, 6, 'Ketchup', '$9.78', 'Condiments', 94, 1);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (2, 57, 'Broccoli', '$6.06', 'Meat', 5, 16);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (3, 49, 'Bacon', '$1.80', 'Beverages', 50, 23);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (4, 32, 'Salmon', '$4.25', 'Dairy', 121, 26);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (5, 78, 'Butter', '$8.65', 'Beverages', 74, 29);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (6, 73, 'Flour', '$3.75', 'Dairy', 217, 13);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (7, 5, 'Bacon', '$1.41', 'Seafood', 245, 22);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (8, 42, 'Chicken Nuggets', '$3.85', 'Meat', 143, 29);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (9, 53, 'Salmon', '$9.81', 'Seafood', 129, 3);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (10, 20, 'Oatmeal', '$8.58', 'Meat', 32, 19);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (11, 49, 'Ground Beef', '$3.04', 'Frozen', 287, 5);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (12, 65, 'Olive Oil', '$0.86', 'Frozen', 280, 3);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (13, 86, 'Waffles', '$0.88', 'Produce', 195, 12);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (14, 12, 'Whole Milk', '$6.47', 'Meat', 322, 2);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (15, 33, 'Ice Cream', '$7.70', 'Frozen', 236, 9);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (16, 97, 'Chicken Nuggets', '$5.34', 'Produce', 155, 30);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (17, 96, 'Sparkling Water', '$0.09', 'Beverages', 197, 9);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (18, 81, 'Mustard', '$3.79', 'Dairy', 67, 6);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (19, 14, 'Pasta', '$5.12', 'Grains', 23, 5);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (20, 42, 'Sparkling Water', '$3.40', 'Meat', 346, 15);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (21, 33, 'Greek Yogurt', '$5.56', 'Condiments', 208, 30);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (22, 8, 'Coffee', '$4.02', 'Seafood', 255, 7);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (23, 89, 'Bread', '$3.95', 'Produce', 114, 20);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (24, 84, 'Pasta', '$1.63', 'Seafood', 92, 28);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (25, 9, 'Whole Milk', '$8.24', 'Condiments', 266, 19);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (26, 73, 'Pasta', '$0.68', 'Beverages', 275, 5);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (27, 5, 'Apples', '$9.67', 'Frozen', 7, 17);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (28, 21, 'Soy Sauce', '$0.14', 'Dairy', 238, 28);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (29, 85, 'White Rice', '$6.34', 'Frozen', 333, 18);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (30, 38, 'Cheddar Cheese', '$1.27', 'Meat', 293, 18);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (31, 36, 'White Rice', '$8.39', 'Meat', 30, 14);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (32, 96, 'Carrots', '$5.39', 'Condiments', 230, 7);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (33, 58, 'Mixed Vegetables', '$9.42', 'Meat', 187, 26);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (34, 86, 'Cheddar Cheese', '$3.46', 'Frozen', 75, 1);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (35, 39, 'Coffee', '$7.80', 'Beverages', 365, 12);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (36, 32, 'Green Tea', '$7.34', 'Produce', 40, 8);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (37, 80, 'Cheddar Cheese', '$5.97', 'Meat', 282, 4);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (38, 82, 'Cheddar Cheese', '$6.89', 'Meat', 163, 24);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (39, 92, 'Hot Sauce', '$8.56', 'Grains', 232, 17);
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category, DefaultSealedShelfLifery, DefaultOpenShelfLife) values (40, 72, 'Sparkling Water', '$3.79', 'Dairy', 261, 28);
