use `green-cart`;

insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (1, 85, 'Whole Milk', '$5.69', 'Seafood');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (2, 94, 'Sparkling Water', '$4.69', 'Dairy');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (3, 4, 'Mixed Vegetables', '$2.06', 'Grains');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (4, 69, 'Butter', '$6.64', 'Beverages');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (5, 23, 'Soy Sauce', '$9.61', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (6, 11, 'Pork Chops', '$6.81', 'Frozen');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (7, 15, 'Oatmeal', '$4.61', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (8, 79, 'Ice Cream', '$3.46', 'Frozen');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (9, 53, 'Broccoli', '$8.53', 'Meat');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (10, 83, 'Frozen Pizza', '$4.69', 'Beverages');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (11, 81, 'Ground Beef', '$2.71', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (12, 99, 'Oatmeal', '$0.87', 'Grains');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (13, 93, 'Olive Oil', '$1.00', 'Produce');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (14, 29, 'Carrots', '$7.10', 'Dairy');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (15, 63, 'Orange Juice', '$8.94', 'Seafood');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (16, 61, 'Cheddar Cheese', '$5.51', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (17, 20, 'Ice Cream', '$4.88', 'Seafood');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (18, 6, 'Green Tea', '$0.01', 'Frozen');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (19, 17, 'Almond Milk', '$8.58', 'Produce');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (20, 82, 'Ice Cream', '$5.55', 'Frozen');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (21, 39, 'Ground Beef', '$8.02', 'Seafood');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (22, 94, 'Pork Chops', '$7.50', 'Produce');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (23, 8, 'Butter', '$5.39', 'Grains');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (24, 50, 'Olive Oil', '$7.77', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (25, 69, 'Hot Sauce', '$8.05', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (26, 96, 'Frozen Pizza', '$6.45', 'Produce');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (27, 79, 'Greek Yogurt', '$0.85', 'Seafood');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (28, 56, 'Waffles', '$5.29', 'Grains');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (29, 6, 'Oatmeal', '$3.11', 'Frozen');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (30, 4, 'Cheddar Cheese', '$8.47', 'Seafood');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (31, 62, 'Soy Sauce', '$0.38', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (32, 49, 'Spinach', '$2.03', 'Frozen');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (33, 1, 'Pork Chops', '$1.31', 'Condiments');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (34, 1, 'Spinach', '$7.12', 'Beverages');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (35, 9, 'Chicken Nuggets', '$5.93', 'Produce');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (36, 47, 'Ice Cream', '$9.71', 'Beverages');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (37, 14, 'Almond Milk', '$2.48', 'Dairy');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (38, 99, 'Pork Chops', '$4.33', 'Beverages');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (39, 14, 'Broccoli', '$4.28', 'Dairy');
insert into FoodGlobal (FoodId, CatId, Name, UnitPrice, Category) values (40, 36, 'Ground Beef', '$5.88', 'Frozen');
