use `green-cart`;

insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (1, 20, 33, 'Ketchup', '16.94', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (2, 24, 6, 'Chicken Nuggets', '14.95', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (3, 55, 19, 'Carrots', '1.54', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (4, 23, 30, 'Chicken Nuggets', '13.73', 10, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (5, 30, 21, 'Salmon', '23.46', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (6, 8, 8, 'Mixed Vegetables', '21.19', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (7, 34, 6, 'Bacon', '13.39', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (8, 53, 20, 'Green Tea', '14.13', 5, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (9, 13, 21, 'Pasta', '8.67', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (10, 38, 31, 'Bacon', '18.72', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (11, 1, 20, 'Mustard', '23.27', 3, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (12, 15, 31, 'Salmon', '4.97', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (13, 29, 36, 'Ice Cream', '0.06', 3, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (14, 31, 40, 'Oatmeal', '13.37', 3, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (15, 22, 11, 'Almond Milk', '15.12', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (16, 69, 19, 'Soy Sauce', '0.98', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (17, 11, 33, 'Oatmeal', '20.52', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (18, 1, 29, 'Mixed Vegetables', '8.11', 1, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (19, 15, 25, 'Flour', '22.50', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (20, 70, 28, 'Almond Milk', '18.53', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (21, 53, 36, 'Flour', '21.22', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (22, 2, 12, 'Chicken Breast', '21.46', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (23, 23, 28, 'Almond Milk', '6.73', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (24, 61, 13, 'Sparkling Water', '11.06', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (25, 36, 24, 'Apples', '9.13', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (26, 5, 36, 'Coffee', '6.92', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (27, 19, 12, 'Cheddar Cheese', '17.48', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (28, 68, 32, 'Mustard', '7.15', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (29, 13, 26, 'Pasta', '0.52', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (30, 27, 10, 'Bread', '5.13', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (31, 1, 28, 'Mustard', '20.81', 6, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (32, 39, 21, 'Flour', '16.52', 10, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (33, 14, 18, 'Ketchup', '16.75', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (34, 60, 38, 'Ground Beef', '22.44', 9, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (35, 61, 27, 'Hot Sauce', '5.29', 1, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (36, 61, 8, 'Greek Yogurt', '17.55', 6, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (37, 11, 35, 'Olive Oil', '11.42', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (38, 56, 18, 'Ketchup', '15.21', 10, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (39, 55, 30, 'Carrots', '23.91', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (40, 61, 25, 'Salmon', '19.35', 2, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (41, 7, 7, 'Whole Milk', '11.60', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (42, 34, 13, 'Frozen Pizza', '5.81', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (43, 29, 26, 'Hot Sauce', '10.86', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (44, 16, 34, 'Bacon', '7.35', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (45, 11, 36, 'White Rice', '24.72', 2, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (46, 56, 16, 'Waffles', '11.21', 2, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (47, 65, 28, 'Orange Juice', '6.66', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (48, 5, 24, 'Waffles', '17.13', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (49, 62, 9, 'Carrots', '24.82', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (50, 65, 38, 'Ice Cream', '14.58', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (51, 33, 8, 'Orange Juice', '24.23', 1, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (52, 40, 39, 'Mixed Vegetables', '6.02', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (53, 64, 22, 'Ground Beef', '20.95', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (54, 52, 22, 'Almond Milk', '15.86', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (55, 69, 6, 'White Rice', '8.66', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (56, 16, 5, 'Cheddar Cheese', '6.19', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (57, 66, 36, 'Pasta', '12.56', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (58, 12, 37, 'Frozen Pizza', '23.99', 1, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (59, 43, 8, 'Oatmeal', '13.74', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (60, 7, 32, 'Sparkling Water', '24.53', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (61, 69, 39, 'Ketchup', '8.46', 6, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (62, 23, 20, 'Greek Yogurt', '5.96', 9, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (63, 7, 7, 'Waffles', '20.88', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (64, 70, 18, 'Almond Milk', '3.78', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (65, 42, 27, 'Apples', '15.58', 3, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (66, 45, 20, 'Hot Sauce', '5.81', 10, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (67, 10, 29, 'Greek Yogurt', '15.28', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (68, 15, 19, 'Cheddar Cheese', '16.45', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (69, 58, 11, 'Bacon', '1.03', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (70, 6, 22, 'Mixed Vegetables', '6.89', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (71, 12, 12, 'Greek Yogurt', '0.04', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (72, 4, 23, 'Spinach', '0.11', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (73, 23, 3, 'Bread', '17.52', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (74, 4, 32, 'Mustard', '18.73', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (75, 20, 1, 'Flour', '10.26', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (76, 33, 20, 'Greek Yogurt', '2.57', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (77, 20, 32, 'Broccoli', '1.24', 10, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (78, 8, 27, 'Ketchup', '18.30', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (79, 42, 32, 'Whole Milk', '19.08', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (80, 39, 4, 'Sparkling Water', '17.41', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (81, 33, 12, 'Ketchup', '9.46', 1, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (82, 18, 22, 'Oatmeal', '10.05', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (83, 4, 25, 'Broccoli', '17.21', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (84, 67, 19, 'Mixed Vegetables', '20.41', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (85, 22, 22, 'Oatmeal', '3.50', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (86, 32, 9, 'Apples', '21.30', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (87, 19, 39, 'Cheddar Cheese', '13.79', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (88, 44, 30, 'Soy Sauce', '13.35', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (89, 45, 25, 'Frozen Pizza', '1.39', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (90, 44, 35, 'Orange Juice', '13.98', 9, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (91, 36, 26, 'Almond Milk', '15.11', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (92, 39, 31, 'Almond Milk', '24.17', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (93, 39, 11, 'Orange Juice', '10.93', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (94, 70, 5, 'Orange Juice', '13.66', 1, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (95, 5, 31, 'Flour', '0.78', 10, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (96, 58, 18, 'Salmon', '24.62', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (97, 43, 18, 'Soy Sauce', '17.09', 10, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (98, 28, 10, 'Frozen Pizza', '13.78', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (99, 62, 29, 'Whole Milk', '20.37', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (100, 5, 23, 'Chicken Breast', '10.49', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (101, 55, 19, 'Ice Cream', '15.80', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (102, 48, 36, 'Soy Sauce', '14.32', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (103, 51, 39, 'Carrots', '4.90', 6, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (104, 8, 40, 'White Rice', '0.78', 3, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (105, 62, 8, 'Bananas', '20.94', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (106, 45, 6, 'Whole Milk', '16.49', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (107, 31, 23, 'Ground Beef', '22.01', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (108, 36, 5, 'Flour', '7.48', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (109, 7, 27, 'Green Tea', '13.84', 8, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (110, 20, 13, 'Olive Oil', '4.35', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (111, 57, 20, 'Apples', '11.52', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (112, 24, 34, 'Cream Cheese', '14.59', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (113, 38, 20, 'Pork Chops', '7.83', 10, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (114, 11, 30, 'Mixed Vegetables', '0.46', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (115, 46, 25, 'Apples', '2.80', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (116, 42, 20, 'Green Tea', '9.12', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (117, 16, 39, 'Spinach', '10.55', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (118, 35, 5, 'Salmon', '21.75', 2, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (119, 21, 40, 'Waffles', '17.63', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (120, 61, 6, 'Ground Beef', '15.41', 6, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (121, 44, 6, 'Oatmeal', '5.15', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (122, 57, 21, 'Bananas', '10.46', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (123, 35, 9, 'Hot Sauce', '10.05', 4, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (124, 40, 40, 'White Rice', '22.29', 7, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (125, 41, 4, 'Green Tea', '3.02', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (126, 62, 37, 'Olive Oil', '13.90', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (127, 12, 13, 'Pasta', '2.30', 2, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (128, 10, 35, 'Waffles', '5.69', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (129, 43, 38, 'Pasta', '19.29', 1, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (130, 45, 40, 'White Rice', '9.44', 6, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (131, 45, 25, 'Carrots', '16.17', 1, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (132, 26, 22, 'Butter', '18.55', 5, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (133, 37, 34, 'Cheddar Cheese', '8.42', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (134, 5, 20, 'Olive Oil', '15.23', 7, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (135, 70, 4, 'Bananas', '5.50', 3, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (136, 54, 3, 'Sparkling Water', '6.76', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (137, 6, 22, 'Greek Yogurt', '15.41', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (138, 11, 9, 'White Rice', '9.21', 10, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (139, 46, 32, 'Apples', '1.12', 8, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (140, 19, 3, 'Whole Milk', '7.82', 3, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (141, 17, 36, 'Cheddar Cheese', '8.86', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (142, 5, 18, 'Chicken Nuggets', '0.31', 9, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (143, 39, 25, 'Butter', '9.38', 2, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (144, 57, 3, 'Butter', '19.38', 5, true);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (145, 13, 32, 'Ketchup', '16.41', 10, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (146, 14, 32, 'Flour', '10.06', 4, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (147, 23, 8, 'Chicken Breast', '17.67', 6, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (148, 61, 32, 'Bacon', '4.09', 5, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (149, 41, 13, 'Cream Cheese', '5.83', 10, false);
insert into GroceryItem (GroceryItemId, GroceryListId, ItemId, Name, Price, Amount, WasBought) values (150, 10, 8, 'White Rice', '19.71', 8, true);
